### ISSUE TITLE
VNet Data Gateway requires Microsoft.PowerPlatform	Resource Provider

### ISSUE THREAD

**Issue by alexjbush** [MicrosoftDocs/data-integration#102]
Hi,

I just spent some time debugging the VNet Data Gateway setup, even with the Microsoft.Network/virtualNetworks/subnets/join/action permission. Turns out I needed the Microsoft.PowerPlatform	Resource Provider to be registered on the subscription.

It might be useful to add this to the FAQ.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee0e9bd-3051-ae24-e7c1-1dc6aa0c137c
* Version Independent ID: 4011df39-116e-dff0-3316-742bc994dc58
* Content: [Virtual network (VNet) data gateway FAQs](https://docs.microsoft.com/en-us/data-integration/vnet/data-gateway-faqs)
* Content Source: [data-integration/vnet/data-gateway-faqs.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-faqs.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @alexjbush for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
