### ISSUE TITLE
Datacenter Region setting information is confusing

### ISSUE THREAD

**Issue by azadehgnia** [MicrosoftDocs/data-integration#103]
[Enter feedback here]
Hi, 
The information about choosing the datacenter region is confusing and might be wrong. I am working on a support ticket with my customer and we are told by support that the region in that setting should always be same as Power BI tenant region even if it's public cloud.

Kind Regards,
Azadeh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a07eaa-023b-fbc8-9508-39411425d096
* Version Independent ID: efb6bb0e-5551-e2b3-4e98-3a34188600f3
* Content: [Set the datacenter region for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-data-region)
* Content Source: [data-integration/gateway/service-gateway-data-region.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-data-region.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Yes, the installer does tell you that if you try to select a different region:
![image](https://user-images.githubusercontent.com/5067358/182536751-58ce13f1-bd1f-49c5-843b-df96ace0a135.png)

**Comment by jonburchel** [comment]
Thanks @azadehgnia for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
