### ISSUE TITLE
Add limitation Virtual network data gateways is a premium-only feature, and will be available only in Power BI Premium workspaces.

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/data-integration#105]
Add on here the limitation that 
Virtual network data gateways is a premium-only feature, and will be available only in Power BI Premium workspaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://docs.microsoft.com/en-us/data-integration/vnet/overview)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by DougKlopfenstein** [comment]
Hi @nathanwlee1 -
This information is available in the [Virtual network data gateway FAQs](https://docs.microsoft.com/data-integration/vnet/data-gateway-faqs) (see the fourth question). Because licensing my change when VNet gateways become generally available, this information was only included in one place so only one instance would need to change if the licensing changes.
