### ISSUE TITLE
On-premises data gateway on the public cloud

### ISSUE THREAD

**Issue by stakemu** [MicrosoftDocs/data-integration#107]
What does the license restriction in the article mean?
[https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq#are-there-any-licensing-prerequisites-required-to-install-gateways---](url)

`But any cloud service might have licensing restrictions on how gateways are used within that service.`

Our customers are considering to install the On-premises data gateway to Azure VM and AWS VM.
AWS has already guided "How to use AWS services with On-premises gateway" in their Japanese blog.
[https://aws.amazon.com/jp/blogs/news/integrate-power-bi-with-amazon-redshift-for-insights-and-analytics/](url)

The license term of On-premises data gateway includes below:
[license.docx](https://github.com/MicrosoftDocs/data-integration/files/6845473/license.docx)

`a.	Installation and Use. You may install and use any number of copies of the software on your devices.`

Does this "your devices" mean to restrict "On-premises data gateway on the public cloud" ?

**Comment by jonburchel** [comment]
Thanks @stakemu for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
