### ISSUE TITLE
Recover-Gateway should be an option

### ISSUE THREAD

**Issue by austinhardy-stt** [MicrosoftDocs/data-integration#111]
Presently there appears to be no way via pwsh cmdlets to recover the data gateway procedurally. Seems like an oversight considering that it can be done via GUI in the installer. But not as an Azure App or using the DataGateway or HAMgmt cmds. Is there any way to recover a Gateway by using the recovery key during Powershell install/setup? There seems to be no way to recover an existing gateway via pwsh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09dff6e8-779b-e03f-594d-47a562fb29cf
* Version Independent ID: 7cbdd803-9fef-a265-d8e2-edd7107afa62
* Content: [Migrate, restore, or take over an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-migrate)
* Content Source: [data-integration/gateway/service-gateway-migrate.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-migrate.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @austinhardy-stt for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
