### ISSUE TITLE
Adding datasource user with override identity flag does not work

### ISSUE THREAD

**Issue by Edgar-Kalkowski** [MicrosoftDocs/data-integration#123]
I am trying to add a service principal user to a gateway with the override effective identity capability like this:

```powershell
Add-DataGatewayClusterDatasourceUser -GatewayClusterId $cluster.Id -GatewayClusterDatasourceId $datasource.Id -DatasourceUserAccessRight ReadOverrideEffectiveIdentity -Identifier $servicePrincipalIdentifier
```

Running this yields the following error:

> Add-DataGatewayClusterDatasourceUser: Cannot validate argument on parameter 'DatasourceUserAccessRight'. The argument "Impersonate" does not belong to the set "Read;ReadOverrideEffectiveIdentity" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

I am not sure where the "Impersonate" comes from since I specified "ReadOverrideEffectiveIdentity". But maybe there is a mismatch in arguments somewhere?

If I specify only "Read" permissions instead of "ReadOverrideEffectiveIdentity" adding the service principal works fine but overall this will not work for me since I need the overridden identity to connect to a SSAS MDX cube.

**Comment by DougKlopfenstein** [comment]
Hi @Edgar-Kalkowski 
This appears to be a customer support issue rather than a documentation issue. For support issues, use the dedicated support channels for the product you're using the on-premises data gateway with:

* For Power BI, visit the [Power BI support page](https://powerbi.microsoft.com/support/).
* For Power Apps, visit the [Power Apps support page](https://powerapps.microsoft.com/support/).
* For Excel, visit the [Excel help & learning page](https://support.microsoft.com/excel).
* For Dynamics 365 Customer Insights, visit the [Dynamics 365 Customer Insights page](https://dynamics.microsoft.com/ai/customer-insights/).
* For Azure Analysis Services, visit the [Azure Analysis Services page](https://azure.microsoft.com/en-us/services/analysis-services).
