### ISSUE TITLE
Why the name on-prem-data-gateway- is not possible to have them on azure

### ISSUE THREAD

**Issue by priyanthaperera01** [MicrosoftDocs/data-integration#136]
I am interested to understand why this the data gateway is names as on-prem-data-gateway??
does this mean that I cannot have a data gateway in my private tenant in azure,  to speak with powerapps in same tenant/subscription  and or another tenant/subscription???
Understanding options of using per-to-peer and or network private vnet.

what is the advantage of using vent peering instead of on-prem-data-gateway??

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks @priyanthaperera01 for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
