### ISSUE TITLE
Gateway setup

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/data-integration#141]
I would like to ask to add to the Note at [https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-high-availability-clusters#high-availability-clusters-for-an-on-premises-data-gateway](url)

Make sure the gateway members in a cluster are running the same gateway version, as different versions could cause unexpected failures based on supported functionality. **It is also recommended to configure same RAM & Processors**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3609538e-bb86-1026-ddd5-dabe93fddc7e
* Version Independent ID: 9dbd2442-7d03-5e24-0882-7a10cb2f71d7
* Content: [Manage on-premises data gateway high-availability clusters and load balancing](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-high-availability-clusters)
* Content Source: [data-integration/gateway/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-high-availability-clusters.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks @MartinaPoddana for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
