### ISSUE TITLE
Unable to install On-prem Data gateway on Azure Public or commercial cloud

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/data-integration#145]
Is there a issue going on with on-prem data gateway installation in Azure commercial and Government cloud?
None of the Microsoft FTE in my team were able to get it install on Azure Commercial cloud.
Customer tried to install it on Azure Government cloud.
We are getting the same error related to Power BI licenses ?
But that is clearly not prerequisite.
There was support ticket# #2204040040007750 and Customer support team wants customer to install PBI license in Azure Gov cloud to get this working.

Is the documentation missing or not up to date?
What are the prerequisite for installing on-prem Data Gateway to access On-Prem DB via Logic App in either Azure Commercial or Government cloud?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks @Anand-Moghe for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
