### ISSUE TITLE
Azure Service Bus sends the pending requests to the gateway

### ISSUE THREAD

**Issue by ghHennie** [MicrosoftDocs/data-integration#150]
If the on-premise data gateway is only configured for outgoing traffic, the on-premise data gateway will initiate a connection to the Azure Service Bus for queued requests (queries) and only then will the service bus send the query to the on-premise data gateway for execution.

If my understanding is correct, we are missing the below activity between point 2 and 3:

>>  The on-premise data gateway will initiate a connection to the Azure Service Bus for queued requests

"
1.	The cloud service creates a query and the encrypted credentials for the on-premises data source. The query and credentials are sent to the gateway queue for processing. For more information about credential encryption in Power BI, see Power BI security whitepaper.
2. The gateway cloud service analyzes the query and pushes the request to Azure Service Bus Messaging.
3. Azure Service Bus sends the pending requests to the gateway. Both the gateway and Power BI service are implemented to only accept TLS 1.2 traffic.
4. The gateway gets the query, decrypts the credentials, and connects to one or more data sources with those credentials.
5. The gateway sends the query to the data source to be run.
6. The results are sent from the data source back to the gateway and then to the cloud service. The service then uses the results.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-onprem-indepth.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by JasonWHowell** [comment]
#please-open

**Comment by jonburchel** [comment]
Thanks @ghHennie for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
