### ISSUE TITLE
Additional details would be helpful.

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/data-integration#16]
It would be a nice improvement to this documentation page if references or links to the other downstream tasks required are mentioned. For instance, after switching this service account you need to update local security policy (impersonate a client after authentication and log on as a service). And, read/write file system permissions need to be set (c:\program files\on-premises data gateway and c:\windows I believe) for the new service account as well. Might save someone some grief. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285b3c81-1498-3497-9021-84227e7f280b
* Version Independent ID: 20064c8f-87fa-ed89-a788-8c9b34968d4d
* Content: [Change the on-premises data gateway service account](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-service-account#feedback)
* Content Source: [data-integration/gateway/service-gateway-service-account.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-service-account.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @sqlchick. I've assigned this issue to the doc owner for review.

**Comment by solanors20** [comment]
It would be good to describe what this account do. The documentation only says what the account don't do (This service account isn't the account used to connect to on-premises data sources. It also isn't the work or school account that you sign in to cloud services with).

**Comment by jonburchel** [comment]
Thanks @sqlchick for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
