### ISSUE TITLE
on-premises but also data sources within private network

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/data-integration#161]
I know its tough to change the name of this product from "on-premises data gateway". But could we please at least change the description in the docs to say secure data transfer between on-premises data **AND** data that resides within private network such as azure sql db, azure storage etc...within private endpoints

_The on-premises data gateway acts as a bridge. It provides quick and secure data transfer between on-premises data, which is data that isn't in the cloud, and several Microsoft cloud services. These services include Power BI, Power Apps, Power Automate, Azure Analysis Services, and Azure Logic Apps._

_By using a gateway, organizations can keep databases and other data sources on their on-premises networks while securely using that on-premises data in cloud services._

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore.

**Comment by jonburchel** [comment]
Thanks @subashsivaji for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
