### ISSUE TITLE
Please specify the minimum address range (CIDR block) required for the subnet

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/data-integration#177]
In Step 2, please specify the minimum `address range (CIDR block)` required for the subnet for Power Platform Virtual Network data gateway. `/24 (256 addresses)` mentioned in the screenshot is quite high for this subnet.

**Comment by JasonWHowell** [comment]
@subashsivaji do you have the URL of which page you were giving feedback for? Thanks, Jason

**Comment by jonburchel** [comment]
Thanks @subashsivaji for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
