### ISSUE TITLE
Can Power BI virtual network gateway span VNet peerings?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/data-integration#199]
Can Power BI virtual network gateway span VNet peerings? It would be great if the documentation could be updated to say anything about it.

Example scenario:

* Source spoke VNet `vnet-powerbi` has Power BI virtual network gateway.
* Hub VNet `vnet-hub` has a NVA in it.
* Destination VNet  `vnet-datalake` has a Data Lake gen 2 / Storage Account using private endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5867016-6164-3563-47bb-1a7b93dc2caf
* Version Independent ID: be22c980-4684-8837-9123-1bcf98e75f06
* Content: [Create virtual network (VNet) data gateways](https://learn.microsoft.com/en-us/data-integration/vnet/create-data-gateways)
* Content Source: [data-integration/vnet/create-data-gateways.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/create-data-gateways.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @o-l-a-v for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
