### ISSUE TITLE
PowerBI Data Gateway on Docker Container

### ISSUE THREAD

**Issue by mafis-hh** [MicrosoftDocs/data-integration#217]
I am trying to bring The PowerBI Data Gateway up and running in a Docker Container. I got quite far, found the DataGateway PowerShell Commandlet, which works preatty easy on a VM. 
I was trying to run it inside a Docker Build step, but the installation hangs and does not proceed. Same as written here: https://community.powerbi.com/t5/Service/Unable-to-install-On-premises-data-gateway-to-Docker-Container/m-p/1800527/thread-id/126711

After research I found the Documentation of the Gateway saying that is is not supported as mentioned on this learn.micrsoft.com site.
```
On "Related considerations" it is written that Gateways aren't supported on
a) Windows Server Core installations
b) Windows Containers
```

My question is, can you please let us know which are the restrictions that prevent the Data Gateway installation on Windows Server Core installations and on Windows Containers in general?
Are there special libraries or programs missing, wich we could install separately (in the Docker container) to get it running?

As both gateways (Synapse / ADF Integration Runtime and PowerBI Data Gateway) are based on .NET, why isn't there a compiled version for Linux available?

I am trying to set up whole data platform architectures as good as possible with Azure PaaS services, which works pretty well, except the gateway services as PowerBI Data Gateway and Integration Runtime of Azure Synapse Analytics.

Of course I know about the option of a "[Virtual network data gateway](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)", but this works only if we can make use of "PowerBI Premium" licenses for all users of a data platform, which is not possible for many customers.

 It would be nice if you can explain some options to integrate the gateways in the PaaS architectures, without using a VM (IaaS).
Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by koureasstavros** [comment]
As per Microsoft documentation the PowerBI VNet can also be used with PPU (Premium Per User) which costs around 20e per user. I am still waiting the license from our IT to test this :)

Although there are some other grey areas like accessing Services instead of Pods and names instead of ips, I already opened another case here https://github.com/MicrosoftDocs/data-integration/issues/272

**Comment by jikuja** [comment]
> As both gateways (Synapse / ADF Integration Runtime and PowerBI Data Gateway) are based on .NET, why isn't there a compiled version for Linux available?

* Probably hard dependencies with Windows daemon architecture. 
* Java-based components(e.g. parquet) is implemented by calling java.dll directly. I'm quite sure it requires platform-specific code
* Then there is a question if all drivers that are shipped with ADF gateway will work on Linux

> My question is, can you please let us know which are the restrictions that prevent the Data Gateway installation on Windows Server Core installations and on Windows Containers in general?

I also would like to know this. And it would be great to know
* if this issue is going to be fixed
* if it is, is there any preliminary ETA or previews?

> It would be nice if you can explain some options to integrate the gateways in the PaaS architectures, without using a VM (IaaS).
Indeed!

**Comment by jonburchel** [comment]
Thanks @mafis-hh for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
