### ISSUE TITLE
What endpoints types can be reached from Power BI Virtual Network Data Gateway?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/data-integration#220]
Said doc lists supported Azure data services for Power BI Virtual Network Data Gateway:

* https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi#supported-azure-data-services

But little or no details about Azure networking. Please add to the documentation:

* Supported endpoint types for said data services.
  * Public endpoint
    * Ex.: With NAT Gateway for static public IP on egress.
  * Service endpoint
  * Private endpoint
* Whether VNet peering is supported.
  * Example scenario: Central Power BI Virtual Network Data Gateway in the hub of a hub/spoke architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @o-l-a-v for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
