### ISSUE TITLE
Recovery key issue into PowerBI Gateway

### ISSUE THREAD

**Issue by koureasstavros** [MicrosoftDocs/data-integration#237]
We use PowerBI Gateway for offering a lot of reports internally though PowerBI Service. Unfortunately, the VM has installed years ago and also PowerBI Gateway installation took place without storing the Recovery Key.

After updating the PowerBI Gateway it asks for the key in order to be restored, currently all reports in all workspaces are not working because the gateway disconnection from the VM.

Is there any way to restore the Recovery Key from the machine or PowerBI Service, or change it without having the old one? I know that probably the answer will be no. In that case is there any way though Microsoft Support?

**Comment by DougKlopfenstein** [comment]
Hi @koureasstavros 
Thanks for the feedback. This issue appears to be a customer support issue rather than a documentation issue. For customer support issues, use the dedicated support channels for the product you're using the gateway with. For example, for Power BI, visit the [Power BI support page](https://support.fabric.microsoft.com/support/).

However, to answer your question, the answer is no. You cannot restore the recovery key from your machine or Power BI service. You can only use the recovery key that was created when the gateway was created. Microsoft does not record your personal recovery key in any way, so we cannot supply one for you to use.
