### ISSUE TITLE
How long does the gateway instance live for?

### ISSUE THREAD

**Issue by vamshisiram** [MicrosoftDocs/data-integration#241]
I create a data source and it created a gateway instance in the subnet i delegated for this. But the Gateway instance is no longer there, as I removed the data source.

Does each data source spin up a new gateway instance in the subnet? and Is the gateway instance deleted after the data source is deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee0e9bd-3051-ae24-e7c1-1dc6aa0c137c
* Version Independent ID: 4011df39-116e-dff0-3316-742bc994dc58
* Content: [Virtual network (VNet) data gateway FAQs](https://learn.microsoft.com/en-us/data-integration/vnet/data-gateway-faqs)
* Content Source: [data-integration/vnet/data-gateway-faqs.yml](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/data-gateway-faqs.yml)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @vamshisiram for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
