### ISSUE TITLE
Port 1433 for Lakehouse connectivity

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/data-integration#246]
Can we update the article to include the port numbers for Lakehouse connectivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by VitalyMCT** [comment]
Please reference https://community.fabric.microsoft.com/t5/Dataflows/Dataflow-Gen2-Issue/td-p/3256928 for official confirmation.

Are there any other items that should be adjusted in this article to account for Fabric scenarios?

**Comment by JasonWHowell** [comment]
We think this is covered here as a troubleshooting FAQ:
https://learn.microsoft.com/en-us/fabric/data-factory/gateway-considerations-output-destinations#network-issues-with-port-1433
> Network issues with port 1433
When using Microsoft Fabric Dataflow Gen2 with an on-premises data gateway, you might encounter issues with the dataflow refresh process. The underlying problem occurs when the gateway is unable to connect to the dataflow staging Lakehouse in order to read the data before copying it to the desired data destination. This issue can occur regardless of the type of data destination being used.

**Comment by VitalyMCT** [comment]
In my experience Fabric customers have little visibility into that separate FAQ page. They expect all network requirements to be consolidated within this page. 

This is not to say that separate FAQ is not useful - it is. However, its relevant aspects need to IMO be integrated into the main doc.

**Comment by JasonWHowell** [comment]
@vitalymct Fabric is still in preview, so potentially the requirements will change, so we didn't blend in Preview content with GA content. It's good feedback and we should consider it soon.

**Comment by jonburchel** [comment]
Thanks @itsnotaboutthecell for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
