### ISSUE TITLE
Clarify FQDN usage

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/data-integration#254]
This "it will strictly use FQDNs only and won't communicate by using IP addresses."  makes no sense.  A FQDN is resolved to an IP.  TCP/IP only works with IP addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by jonburchel** [comment]
Thanks @dbrownems for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
