### ISSUE TITLE
Clarify "sovereign clouds" - explicitly list where it is, isn't supported

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/data-integration#260]
The line "This feature is currently not supported in sovereign clouds" is a little confusing with our new "Microsoft Cloud for Sovereignty". I'm pretty sure this intended to mean that it isn't supported with Office 365 GCC, GCC-H, DOD. And I assume that it will eventually come to GCC before the other two.

Can this line be updated to list which types of tenants are not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/overview#limitations)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @npherson for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
