### ISSUE TITLE
There is no information about External DNS setup 

### ISSUE THREAD

**Issue by koureasstavros** [MicrosoftDocs/data-integration#272]
While using Azure WebApp and VNET Integration in order the WebApp to access Internal Kubernetes Resources with external names there is a special configuration like below:

Add external domain in the load-balancer configmap (coredns-custom) into Kubernetes
`data:
  test.override: k8s_external mycluster.local`

Set the load-balancer service as azure-internal into Kubernetes
`annotations:
  service.beta.kubernetes.io/azure-load-balancer-internal: 'true'`

Set an Environmental Variable into Azure WebApp

`WEBSITE_DNS_SERVER = <the internal ip of your load-balancer (which resides into POD subnet)>`

For Power-BI which also uses the NVet Integration there is no information how PowerBI is going to resolve the names into Kubernetes Cluster like Webapp does (instead of service internal IPs / from internal load balancer). This is a special case when connecting to database inside Kubernetes Cluster with Internal Load Balancer though service name:

`myservice.mynamespace.mycluster.local`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5091585c-6eae-176b-f97b-6e7bf5f18d3f
* Version Independent ID: ece61ded-aee6-c780-25ef-d5c57161df7b
* Content: [Use virtual network (VNet) data gateway and data sources in Power BI](https://learn.microsoft.com/en-us/data-integration/vnet/use-data-gateways-sources-power-bi)
* Content Source: [data-integration/vnet/use-data-gateways-sources-power-bi.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/use-data-gateways-sources-power-bi.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @koureasstavros for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
