### ISSUE TITLE
Licensing SKUs and GA for VNET Data Gateway

### ISSUE THREAD

**Issue by mmcguinness** [MicrosoftDocs/data-integration#290]
Hi, we're wanting to implement VNET Data Gateway with Power BI and a SQL private endpoint.

Is it possible to get some clarification on the Power BI or Fabric SKUs required to use this capability (now, and at GA), and is there a release plan timeline for GA? I couldn't find VNET Data Gateway on the roadmaps.

Thanks,
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47e61c8-a5b8-0a8b-06dd-c242a0acd06c
* Version Independent ID: e80385c1-b254-525d-b5ec-2b653e7763d8
* Content: [What is a virtual network (VNet) data gateway (Preview)](https://learn.microsoft.com/en-us/data-integration/vnet/overview)
* Content Source: [data-integration/vnet/overview.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/overview.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @mmcguinness for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
