### ISSUE TITLE
Gateway Performance PBI template does not work fails to load

### ISSUE THREAD

**Issue by KevinInKy** [MicrosoftDocs/data-integration#294]
The Gateway Performance PBI template  does not work.  When loading it takes excruciatingly long to load.  For 1 day worth of logs it took almost 24 hours to only end with an error message.   The error message is QueryStartReport.  The field "QueryType" already exists in the record.

<img width="253" alt="2023-12-20 09_01_01- EXTERNAL  RE_ Case 2312140040011004  Your   - TrackingID#2312140040011004 _ M" src="https://github.com/MicrosoftDocs/data-integration/assets/154441643/e3f15241-6432-481d-823f-8305c6acf5b7">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @KevinInKy 
Thank you for your feedback!

This seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for gateways in Power BI, go to [Power BI Support](https://powerbi.microsoft.com/support/). You can also ask for help in the [Power BI forum](https://community.fabric.microsoft.com/t5/Desktop/bd-p/power-bi-designer).
