### ISSUE TITLE
Can you automate this?

### ISSUE THREAD

**Issue by prashantnayak** [MicrosoftDocs/data-integration#301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5867016-6164-3563-47bb-1a7b93dc2caf
* Version Independent ID: be22c980-4684-8837-9123-1bcf98e75f06
* Content: [Create virtual network (VNet) data gateways](https://learn.microsoft.com/en-us/data-integration/vnet/create-data-gateways#step-3-create-a-vnet-data-gateway)
* Content Source: [data-integration/vnet/create-data-gateways.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/vnet/create-data-gateways.md)
* Service: **virtual-network-data-gateway**
* GitHub Login: @nikkiwaghani
* Microsoft Alias: **nikkiwaghani**

**Comment by jonburchel** [comment]
Thanks @prashantnayak for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
