### ISSUE TITLE
Is this for Windows 10 Enterprise Client?

### ISSUE THREAD

**Issue by wongsunn** [MicrosoftDocs/data-integration#303]
[I need help with updating a Network Drive Folder by saving attachment ASAP when an Outlook 365 Email Arrive Friday night to overcome my unavailability to login Saturday and Sunday.

 

For Windows 10 Enterprise Client, my latest questions:
(1) application for DLP Policy change requires Environment Name and URL; how to find out?
(2) since additional Install of on-premises data gateway to download 
(A) is local computer running and login required?
(B) how to get Windows Server 2012 R2 for Windows Client?

[YouTube demo of Save Email to File System requires Data Gateway in Local Computer?](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkdkb3pURUtOZHpEZGRWT1J0YjBjOGd2RTV1UXxBQ3Jtc0trUjhhNzJUSm5XeEdDUnprMllKNlhpdGtSWnFiZERyb042TkVCRFBqYkZJeEZWUkxCTzhMazdqTjYzdVAxV25FaGxCTzhnV0ZORm5HRjZ3dE16cy1CaHY5b05TZi0zYUhzZGZScEFoNzZ0a3c5ZFV0OA&q=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdata-integration%2Fgateway%2Fservice-gateway-install%23download-and-install-a-standard-gateway&v=japxQqabFgQ) 

 

My initial question:

defining custom path to Enterprise Network Drive Folder where email attachment is to go.

Initially, I start with Template but run into problem with create File System (error message shown below).

 

There is alternative as contributed by DamoBird365; do I still need to create File System? 

https://pnp.github.io/blog/post/save-an-email-attachment-to-a-custom-path-with-power-automate/>  

 

 

Failed to create connection for connection id '/providers/Microsoft.PowerApps/apis/shared_filesystem/connections/shared-filesystem-09d66db8-ad72-45d6-89ea-39ad518a1ee2'. Connection creation/edit of 'shared_filesystem' has been blocked by Data Loss Prevention (DLP) policy 'DLP Personal Productivity'.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-install#download-and-install-a-standard-gateway)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by jonburchel** [comment]
Thanks @wongsunn for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
