### ISSUE TITLE
The pbix report doesn't work. The is no "QueryExecutionStartTimeUTC" in On Premise Gateway export logs

### ISSUE THREAD

**Issue by zayca** [MicrosoftDocs/data-integration#304]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#gateway-performance-monitoring-public-preview)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by jonburchel** [comment]
Thanks @zayca for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
