### ISSUE TITLE
Confirm core and memory requirements / include azure vm requirements

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/data-integration#36]
it seems odd that we are asking for 8 cores but only 8 gigs of ram can someone confirm that this is indeed correct? it would be nice to update this article to include some general guidance on the best Azure VM sizes to use as well. 

Here is an example section where the ADF team provides guidance for sizing an azure vm for an SSIS IR
https://docs.microsoft.com/en-us/azure/data-factory/configure-azure-ssis-integration-runtime-performance#azuressisnodesize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install#feedback)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @jasonhorner for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
