### ISSUE TITLE
SharePoint field "Approval Status" not available on-premises data gateway

### ISSUE THREAD

**Issue by mschaaks** [MicrosoftDocs/data-integration#37]
Situation: 
Perform action on a list item trigger using the SharePoint built-in content approval field called "Approval Status". 

Components used: 
Logic App + On-premises Data Gateway configured to connect to SharePoint on-premises.

Problem: 
When using the on-premises data gateway together with the SharePoint trigger "item create or change" to get the value of the SharePoint field "Approval Status", internal name = "_ModerationStatus", this field cannot be resolved. It seems to be related to the data gateway connection, because using the SharePoint Online connector does present the ability to pick the returned Approval Status field value.

Question:
Is this a bug/defect in the data gateway connector or a known limitation ?

**Comment by DougKlopfenstein** [comment]
Hi @mschaaks 
This seems to be product feedback or a request for product support rather than documentation feedback. For information about product feedback or customer support for gateways in Azure Logic Apps, go to [Azure Logic Apps Q&A](https://docs.microsoft.com/answers/topics/azure-logic-apps.html).
