### ISSUE TITLE
remove a computer from a gateway?

### ISSUE THREAD

**Issue by fpk3** [MicrosoftDocs/data-integration#40]
It doesn't look like there's a way to remove a machine from a gateway cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20180bfa-f4ab-224a-d089-58a06dbf4ac3
* Version Independent ID: f4ab3a3c-397d-01d1-f6d2-05e9085770a1
* Content: [Manage an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage#feedback)
* Content Source: [data-integration/gateway/service-gateway-manage.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-manage.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @fpk3 for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
