### ISSUE TITLE
Data temporary storage on the gateway machine

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/data-integration#51]
The documentation states "In step 6, queries like Power BI refreshes and Azure Analysis Services refreshes can return large amounts of data. For such queries, data is temporarily stored on the gateway machine.".

This sentence is ambiguous as "large amounts of data" as well as "temporarily" stored is not defined. Please link to additional documentation for:

- what criteria decides that my on-premises data would be stored on gateway machines
- for how long it would be stored there
- how it is actually stored (i.e. encrypted?)
- Is the data stored in the same geo-region as my tenant region
- What queries are affected? Also Power Automate, Power Apps etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-indepth.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @DennisGaida for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
