### ISSUE TITLE
Needs link to .Net Downloads

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/data-integration#54]
You mention near the start it requires .Net 4.6 or 4.7.2, but no link to get it. It would be helpful if you included the right place to download those for Windows Server 2012 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install#feedback)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @pcgeekus for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
