### ISSUE TITLE
Should you rename Service Bus  to Azure Relay?

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/data-integration#69]
Please Update the article to rename Service Bus  to Azure Relay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c654ef3-6a36-2f86-9640-1585efabfd0a
* Version Independent ID: 2c3c6a6a-d095-f057-b225-dc1206b2d72a
* Content: [On-premises data gateway architecture](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-indepth)
* Content Source: [data-integration/gateway/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-indepth.md)
* Technology: **on-premises-data-gateway**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by JasonWHowell** [comment]
@DougKlopfenstein let's discuss with @spelluru when he returns

**Comment by JasonWHowell** [comment]
Agreed, it is called Azure Relay clearly in the installer:
![image](https://user-images.githubusercontent.com/5067358/182537506-fa04fb7d-22ed-458f-b856-7370e7ebdbca.png)

**Comment by spelluru** [comment]
@JasonWHowell @DougKlopfenstein - so sorry. It doesn't show up in queries for Git issues (because it doesn't have azure-relay tag on it). 

Yes. Azure Relay is the service that lets on-prem components/services to communicate with services in the cloud. We should get the on-prem gateway PM to give us the updated image (Azure Service Bus -> Azure Relay) and then change the text ourselves. Thanks.

**Comment by DougKlopfenstein** [comment]
@MNF @spelluru 
Thanks for the feedback. All instances of Azure Service Bus have been changed to Azure Relay (including the images).
