### ISSUE TITLE
Managing request Failures and Reasons why I would lower capacity

### ISSUE THREAD

**Issue by binaryjam** [MicrosoftDocs/data-integration#73]
[Enter feedback here]
In the case of high availability,  you state that if all the gateways are at max the request can fail, some link to a guide on how to spot these occurrence for gateway managers would be of help here.

Regarding the processor /mem max limits,   So I can set this to 80 and then the gateway stops receiving requests and it goes to another if available.   Why would I set this ?  All Ive done is reduce the max capacity of this server making it more likely it goes elsewhere or fails,   can you provide details of WHY I would want to do this and risk request failures ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3609538e-bb86-1026-ddd5-dabe93fddc7e
* Version Independent ID: 9dbd2442-7d03-5e24-0882-7a10cb2f71d7
* Content: [Manage on-premises data gateway high-availability clusters and load balancing](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-high-availability-clusters)
* Content Source: [data-integration/gateway/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-high-availability-clusters.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @binaryjam for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
