### ISSUE TITLE
Included Simba Redshift driver requires Visual C++ Redistributable

### ISSUE THREAD

**Issue by ErnestF-GH** [MicrosoftDocs/data-integration#74]
The included Simba Redshift ODBC driver requires the Visual C++ Redistributable for Visual Studio 2015. This requirement is not listed in the prerequisites and the installer does not include it. If you don't have the runtime installed, you receive an error similar to the following:

ODBC: ERROR [IM003] Specified driver could not be loaded due to system error  126: The specified module could not be found. (Simba Amazon Redshift ODBC Driver, C:\Program Files\On-premises data gateway\m\ODBC Drivers\Simba Amazon Redshift ODBC Driver\AmazonRedshiftODBC_sb64.dll).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c51a10c-d90c-7690-0979-cd8ce37234c8
* Version Independent ID: 2da65f4c-f128-40b8-1a2b-5ae72c4252d6
* Content: [Install an on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install)
* Content Source: [data-integration/gateway/service-gateway-install.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-install.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @ErnestF-GH for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
