### ISSUE TITLE
new question

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/data-integration#80]
Hi,

it would be great if we can have following question + the answer in this FYQ list:
"Can the same Gateway be used for environments in different tenants?"

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c093e8d2-49bb-cf51-02a8-d7792913a5ad
* Version Independent ID: 8fe1e76c-37e2-c6a8-4667-6578164d5b1e
* Content: [On-premises data gateway FAQ](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq)
* Content Source: [data-integration/gateway/service-gateway-onprem-faq.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-onprem-faq.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @MichaelWeberMSFT for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
