### ISSUE TITLE
Correct and enhancement

### ISSUE THREAD

**Issue by jamserra** [MicrosoftDocs/data-integration#82]
Page says "When you turn this feature on, three new log files are created" but then lists four log files.  Also, can you explain the details of what additional logging is captured when turning on "additional logging" on the data gateway and where it is located?  Is that info included in the Gateway Performance PBI template file?  Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance#slow-performing-queries)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @jamserra for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
