### ISSUE TITLE
Types of ApplicationFileTraceListeners

### ISSUE THREAD

**Issue by ZdenekSoldan** [MicrosoftDocs/data-integration#88]
I would like to more understand the GatewayInfo.log, GatewayErrors.log, and GatewayNetwork.log files but there is very poor documentation page https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-log-files with no details.
What are the ApplicationFileTraceListeners Microsoft.PowerBI.DataMovement.Pipeline.Common.Diagnostics.RotatableFilesManagerTraceListener and Microsoft.PowerBI.DataMovement.Pipeline.Common for? Are there more available types of listeners?

**Comment by JasonWHowell** [comment]
@DougKlopfenstein do we have a CSS contact that could help flesh out the logging pages? @joshger do you know anyone?

**Comment by JoshGer** [comment]
@JasonWHowell  - I'm not sure about this one. @tusharvaja - Is there someone on the PBI supportability team who can help add more GW log details to the doc?

**Comment by JasonWHowell** [comment]
Close/open to trigger our bot. Please ignore. #please-close

**Comment by jonburchel** [comment]
Thanks @ZdenekSoldan for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
