### ISSUE TITLE
Group Managed Service Account for On-Premise gateway

### ISSUE THREAD

**Issue by hiteshtulsani** [MicrosoftDocs/data-integration#91]
Is it possible to use a gSMA for data gateway service account as mentioned on the page? Are there any examples of what permissions the SMA needs and how to setup? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285b3c81-1498-3497-9021-84227e7f280b
* Version Independent ID: 20064c8f-87fa-ed89-a788-8c9b34968d4d
* Content: [Change the on-premises data gateway service account](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-service-account)
* Content Source: [data-integration/gateway/service-gateway-service-account.md](https://github.com/MicrosoftDocs/data-integration/blob/master/data-integration/gateway/service-gateway-service-account.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by ld0614** [comment]
+1 I'm currently trying to set up a gMSA for the service account as per the documentation. despite Test-ADServiceAccount returning true I get 'Service account or password is incorrect' when attempting to use it in the data connector gateway

**Comment by jonburchel** [comment]
Thanks @hiteshtulsani for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question. If this issue is still ongoing, please open a support incident through the Azure Portal by selecting the main top left menu, and then Help + Support, to provide details and create your incident that will be addressed by one of our support engineers. Because this issue does not relate to documentation, we are closing this issue. #please-close
