### ISSUE TITLE
Clarification on documentation

### ISSUE THREAD

**Issue by valenciajdev** [MicrosoftDocs/data-integration#98]
It will be beneficial to clarify that [Step 2](https://docs.microsoft.com/en-us/data-integration/vnet/create-data-gateways#step-2-associate-the-subnet-to-microsoft-power-platform) will ensure that all network traffic will be kept at the Azure Region selected for the VNet.
For [Step 3](https://docs.microsoft.com/en-us/data-integration/vnet/create-data-gateways#step-3-create-a-vnet-data-gateway), please clarify that the gateway will communicate with the PBI Home tenant and what is passed thru it. This confuses customers (none technical savvy) when they are using PBI Premium multi-geo and VNets.

**Comment by jonburchel** [comment]
Thanks @valenciajdev for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
