### ISSUE TITLE
Event Viewer IDs for gateway issues

### ISSUE THREAD

**Issue by KrzysztofGod** [MicrosoftDocs/data-integration#99]
Is there a way to get a list of possible IDs of events in Event Viewer for gateway? We would like to setup monitoring with SolarWinds to check for events like "gateway is unreachable" but we are not sure if it puts such the event in Event Viewer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a144b27-04b6-5d42-9c9f-79bb4cc6730b
* Version Independent ID: 7b00f680-f3a8-3502-94b5-5ca37d36f432
* Content: [Monitor and optimize on-premises data gateway performance](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance)
* Content Source: [data-integration/gateway/service-gateway-performance.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-performance.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by jonburchel** [comment]
Thanks @KrzysztofGod for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
